###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "id": "Usuario_2",
  "password": "{noop}1234"
}


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "id": "Usuario_2",
  "password": "1234"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "id": "Root",
  "password": "1234"
}
###
GET http://localhost:8080/usuarios
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJSb290IiwiaWF0IjoxNzY1MjEwMjE5LCJleHAiOjE3NjUyMTExMTksIm5iZiI6MTc2NTIxMDIxOSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdfQ._fXbeoGvpzBURygRiGraFRfdQ_V14ywinX3ZoXAyPJWIDOnQt5ppz_1ATnGFCsoTskgYUBpVd3AJR_4kwQHHDQ

###
GET http://localhost:8080/usuarios/Usuario_1
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJSb290IiwiaWF0IjoxNzY1MjEwMjE5LCJleHAiOjE3NjUyMTExMTksIm5iZiI6MTc2NTIxMDIxOSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdfQ._fXbeoGvpzBURygRiGraFRfdQ_V14ywinX3ZoXAyPJWIDOnQt5ppz_1ATnGFCsoTskgYUBpVd3AJR_4kwQHHDQ

###
DELETE http://localhost:8080/usuarios/Usuario_2
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJSb290IiwiaWF0IjoxNzY1MjEwMjE5LCJleHAiOjE3NjUyMTExMTksIm5iZiI6MTc2NTIxMDIxOSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdfQ._fXbeoGvpzBURygRiGraFRfdQ_V14ywinX3ZoXAyPJWIDOnQt5ppz_1ATnGFCsoTskgYUBpVd3AJR_4kwQHHDQ
