###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "id": "comisario_45",
  "password": "1234"
}

###
GET http://localhost:8080/usuarios
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJjb21pc2FyaW9fNDUiLCJpYXQiOjE3NjQ5NTIzNzgsImV4cCI6MTc2NDk1MzI3OCwibmJmIjoxNzY0OTUyMzc4LCJyb2xlcyI6W119.IcRZbQuWQh59KPBpHcByifAgoLguh4rA0RWXduksOv0y31Eg6u6gz0vr8G8MIvmf_GadDPFN6D-Won5DWk1EDg