###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "id": "usuario15",
  "nombre": "Juan Perez",
  "email": "juan.perezz@usc.es",
  "password": "passwordSeguro123",
  "habitacion": 101,
  "nacimiento": "2000-05-20",
  "telefono": 600123456
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "id": "usuario15",
  "password": "passwordSeguro123"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "id": "Root",
  "password": "passwordSeguro123"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "id": "Root",
  "password": "1234"
}
###
GET http://localhost:8080/usuarios
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJSb290IiwiaWF0IjoxNzY1ODE0NzUxLCJleHAiOjE3NjU4MTU2NTEsIm5iZiI6MTc2NTgxNDc1MSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdfQ.ewoLdFXpQIZ1ZA3nd2W0yg-2v2lu3Pt_y3Rndu1OiVHQWTx-fBlCvfJAd7LPvqbDnW0okPBftvN-m7fgyV6fBg
Set-Cookie: __Secure-RefreshToken=09204d68-0096-4305-a44f-e64b7ea43033; Path=/auth/refresh; Max-Age=604800; Expires=Mon, 22 Dec 2025 16:05:51 GMT; Secure; HttpOnly; SameSite=STRICT

###
GET http://localhost:8080/usuarios/usuario15
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJSb290IiwiaWF0IjoxNzY1ODE0NzUxLCJleHAiOjE3NjU4MTU2NTEsIm5iZiI6MTc2NTgxNDc1MSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdfQ.ewoLdFXpQIZ1ZA3nd2W0yg-2v2lu3Pt_y3Rndu1OiVHQWTx-fBlCvfJAd7LPvqbDnW0okPBftvN-m7fgyV6fBg
Set-Cookie: __Secure-RefreshToken=09204d68-0096-4305-a44f-e64b7ea43033; Path=/auth/refresh; Max-Age=604800; Expires=Mon, 22 Dec 2025 16:05:51 GMT; Secure; HttpOnly; SameSite=STRICT

###
DELETE http://localhost:8080/usuarios/usuario3
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJSb290IiwiaWF0IjoxNzY1ODE0NzUxLCJleHAiOjE3NjU4MTU2NTEsIm5iZiI6MTc2NTgxNDc1MSwicm9sZXMiOlsiUk9MRV9BRE1JTiJdfQ.ewoLdFXpQIZ1ZA3nd2W0yg-2v2lu3Pt_y3Rndu1OiVHQWTx-fBlCvfJAd7LPvqbDnW0okPBftvN-m7fgyV6fBg
Set-Cookie: __Secure-RefreshToken=09204d68-0096-4305-a44f-e64b7ea43033; Path=/auth/refresh; Max-Age=604800; Expires=Mon, 22 Dec 2025 16:05:51 GMT; Secure; HttpOnly; SameSite=STRICT

###
POST http://localhost:8080/salas
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJSb290IiwiaWF0IjoxNzY1MjExNDcyLCJleHAiOjE3NjUyMTIzNzIsIm5iZiI6MTc2NTIxMTQ3Miwicm9sZXMiOlsiUk9MRV9BRE1JTiJdfQ.vmDK6j4nbj9QrF5zYbWK_Km-1DHsN4PrOk7tJ7SKzjWkw4WsUXTGIxnEzdIe0QmKUwQkXJ8_KCBBay5_7pE8Dw
Content-Type: application/json

{
    "id": 1254,
    "aforo": 12,
    "descripcion": "Sala músical con Batería",
    "responsableActual": null
}

###
POST http://localhost:8080/reservas
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJVc3VhcmlvXzIiLCJpYXQiOjE3NjUyMTc1MzIsImV4cCI6MTc2NTIxODQzMiwibmJmIjoxNzY1MjE3NTMyLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.Qjj_3ybRYM8jB2Os0MwYJcKPir6LJbn_HF66f4446tyhKRU7hCQ01pv7t7z4TNpfq0uOtai2F_QHq1BJIIkqDw
Content-Type: application/json

{
  "id": "ID2",
  "sala": {
    "id": 3
  },
  "usuario": {
    "id": "Usuario_2"
  }
}

###
DELETE http://localhost:8080/reservas/ID2
Authorization: Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJVc3VhcmlvXzIiLCJpYXQiOjE3NjUyMTg2MjksImV4cCI6MTc2NTIxOTUyOSwibmJmIjoxNzY1MjE4NjI5LCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.-mW3SHoAV5PnP2yW4b-CbLjXpANTGH_wwQ8Xf2l4wAoLzzFcrFYDQrBViKqJwvVdbHgFEVLGwK914PS95-eZCg
